### PR TITLE
Update to 0.83.0 and re-generate factories for new features

### PR DESCRIPTION
**Pull request by j1mr10rd4n**
This PR updates the dependency on semantic-ui-react to 0.83.0, enabling support for new features in semantic-ui 2.4.0 including placeholders and placeholder-segments, clearable dropdowns and improved flexbox models.

### CODE REVIEW

**Comment by j1mr10rd4n** [comment]
I realise this repo is unmaintained - however, I found the pre-generated factories very useful in my current project.

**Comment by awkay** [comment]
Hey, it's maintained as long as ppl want to maintain it :)

**Comment by awkay** [comment]
Are you interested in being the maintainer on this?  It does not seem to generate much noise, and all you'd really have to do is update the readme to remove the "not maintained" warning and do clojars releases.

**Comment by awkay** [comment]
Released 2.0.4.  I also update the README a bit, and also added a suggestion that some optimizations could be done to make this library help with build size.

**Comment by j1mr10rd4n** [comment]
Hi Tony, yes I'd be interested in helping with the maintenance on this library. I've created https://github.com/fulcrologic/semantic-ui-wrapper/pull/7 with some work on the optimization you suggested.

**Pull request merged**
